PM / Suspend: use time_to_tm for printing timestamps
When CONFIG_RTC is disabled for any reason, we run into a link error
in the suspend code:

suspend.c:(.text+0x39764): undefined reference to `rtc_time_to_tm'

rtc_time_to_tm() is specific to rtc drivers, but there is an almost-identical
function named time_to_tm that we can use instead.

kernelci reported the problem only on android-3.18, but it also exists
in 4.4 and 4.9, which have the same code.

Log: https://kernelci.org/build/id/59106be259b514d00bb12d50/logs/
Fixes: 195382b8828f ("PM / Suspend: Print wall time at suspend entry and exit")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Greg Kroah-Hartman <gregkh@google.com>